import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ToastProvider from '@/app/components/providers/toast-provider';

const reckless = localFont({
  src: '../public/fonts/reckless-uprights-variable.woff2',
  variable: '--font-reckless',
});
const roobert = localFont({
  src: '../public/fonts/roobert-pro-variable.woff2',
  variable: '--font-roobert',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roobert.variable} ${reckless.variable} antialiased`}
    >
      <body className="root">
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
